name: CI
on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ "*" ]

permissions:
  contents: read

jobs:
  publish:
    name: Publish
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/wittenbude/envsubst
          tags: |
            type=edge,enable={{is_default_branch}}
            type=ref,event=tag
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
